### ISSUE TITLE
Error Message Includes Full Credit Card Details

### ISSUE THREAD

**Issue by stevekessler** [mlutfy/ca.bidon.reporterror#28]
I got an email with the full report for an error based on this backtrace.  It included the full creditcard number in an array.  I am wondering if there is someway to sanitize this data when we know there is transaction data in the report.  

I am using 4.7.29 and the payment processor is Authorize.net.  

***BACKTRACE***

```
#0 /home/domain/public_html/sites/default/files/civicrm/ext/ca.bidon.reporterror/reporterror.php(266): reporterror_civicrm_generatereport("Site Name", (Array:2), NULL, (Array:0))
#1 /home/domain/public_html/sites/all/modules/civicrm/CRM/Core/Error.php(365): reporterror_civicrm_handler((Array:2))
#2 /home/domain/public_html/sites/all/modules/civicrm/CRM/Utils/Request.php(120): CRM_Core_Error::fatal("Could not find valid value for id")
#3 /home/domain/public_html/sites/all/modules/civicrm/CRM/Event/StateMachine/Registration.php(52): CRM_Utils_Request::retrieve("id", "Positive", Object(CRM_Event_Controller_Registration), TRUE)
#4 /home/domain/public_html/sites/all/modules/civicrm/CRM/Event/Controller/Registration.php(47): CRM_Event_StateMachine_Registration->__construct(Object(CRM_Event_Controller_Registration), TRUE)
#5 /home/domain/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(304): CRM_Event_Controller_Registration->__construct("Event Registration", TRUE, "null", NULL, "false")
#6 /home/domain/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:15))
#7 /home/domain/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#8 /home/domain/public_html/sites/all/modules/civicrm/drupal/civicrm.module(448): CRM_Core_Invoke::invoke((Array:3))
#9 /home/domain/public_html/includes/menu.inc(527): civicrm_invoke("event", "register")
#10 /home/domain/public_html/index.php(21): menu_execute_active_handler()
#11 {main}
```

I am not sure how to help write a patch for this but I am glad to test.  

Thanks,
Steve

**Comment by mlutfy** [comment]
Hi Steve,

Thanks for reporting the issue. This is pretty bad indeed. The extension should have some safeguards around this, but there must be a case where it's not covered.

Could you provide an example of what it looked like? (while fully obfuscating the card number, of  course). Was it in the GET / POST data?

Mathieu

**Comment by stevekessler** [comment]
@mlutfy 

Here is POST data specifically.  I am also including the entire email (obfuscated of course) so you have as much information as I can give you.  

***POST***
qfKey:              63ab4dbb89206e52bf2de9d34e150756_2611
entryURL:           https://crm.domain.org/civicrm/event/register?reset=1&amp;id=112
hidden_processor:   1
scriptFee:
scriptArray:
priceSetId:         164
payment_processor_id:1
bypass_payment:
_qf_default:        Register:upload
MAX_FILE_SIZE:      2097152
additional_participants:1
first_name:         FirstName
last_name:         LastName 
email-Primary:      email@email.com
phone-1-2:          7201234567
custom_134:         Array
(
    [Board Member] =>
    [Board President] =>
    [Project Captain] =>
    [Recipient] =>
    [Sponsor] =>
    [Volunteer] =>
    [Proud Supporter] => 1
    [Other] => 1
)
custom_135:         Proud collaborator!
custom_139:
custom_136:         Continued independence, enrichment and happiness for ---- recipients.
custom_138:
price_294:          2
price_289:
price_290:
price_291:
price_292:
price_293:
credit_card_type:   Amex
credit_card_number: 300000000000000
cvv2:               4000
credit_card_exp_date:Array
(
    [M] => 3
    [Y] => 2020
)

billing_first_name: FirstName
billing_middle_name:
billing_last_name:  LastName
billing_street_address-5:134 123 Street
billing_city-5:     Denver
billing_country_id-5:1228
billing_state_province_id-5:1005
billing_postal_code-5:80223
_qf_Register_upload:Continue

--- 
**Full Post**

There was a CiviCRM error at Organization.
Date: 2018-02-27T08:18:45-07:00



***ERROR***
message:            Could not find valid value for id
code:

***LAST ERROR***


***ANONYMOUS USER***
REMOTE_ADDR: 0.0.0.0
HTTP_USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36


***SESSION***
CiviCRM:            Array
(
    [qfPrivateKey] => 18e41239bc2ccaec2e769f8c3f75649c1ce46a8439823f050b132c236500fd66
    [qfSessionID] => fTLfI44E3JnUsnft0ToYJPWDY_T5xDHOB-145oGkfAo
    [entryURL] => https://crm.domain.org/civicrm/event/register?reset=1&amp;id=112
    [CRM_Event_Controller_Registration_63ab4dbb89206e52bf2de9d34e150756_2611] => Array
        (
            [qfKey] => 63ab4dbb89206e52bf2de9d34e150756_2611
        )

)


***SERVER***
REDIRECT_REDIRECT_UNIQUE_ID:WpV21QW7nE7Q@zaHv-t4twAAAAI
REDIRECT_REDIRECT_SCRIPT_URL:/civicrm/event/register
REDIRECT_REDIRECT_SCRIPT_URI:https://crm.domain.org/civicrm/event/register
REDIRECT_REDIRECT_protossl:s
REDIRECT_REDIRECT_HTTP_AUTHORIZATION:
REDIRECT_REDIRECT_HTTPS:on
REDIRECT_REDIRECT_SSL_TLS_SNI:crm.domain.org
REDIRECT_REDIRECT_STATUS:200
REDIRECT_UNIQUE_ID:     
REDIRECT_SCRIPT_URL:/civicrm/event/register
REDIRECT_SCRIPT_URI:https://crm.domain.org/civicrm/event/register
REDIRECT_protossl:  s
REDIRECT_HTTP_AUTHORIZATION:
REDIRECT_HTTPS:     on
REDIRECT_SSL_TLS_SNI:crm.domain.org
REDIRECT_HANDLER:   application/x-httpd-ea-php70
REDIRECT_STATUS:    200
UNIQUE_ID:         
SCRIPT_URL:         /civicrm/event/register
SCRIPT_URI:         https://crm.domain.org/civicrm/event/register
HTTPS:              on
SSL_TLS_SNI:        crm.domain.org
HTTP_HOST:          crm.domain.org
HTTP_CONNECTION:    keep-alive
CONTENT_LENGTH:     5447
HTTP_CACHE_CONTROL: max-age=0
HTTP_ORIGIN:        https://crm.domain.org
HTTP_UPGRADE_INSECURE_REQUESTS:1
CONTENT_TYPE:       multipart/form-data; boundary=----WebKitFormBoundarynDw5v2USGzHa6hI7
HTTP_USER_AGENT:    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
HTTP_ACCEPT:        text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
HTTP_REFERER:       https://crm.domain.org/civicrm/event/register?reset=1&id=112
HTTP_ACCEPT_ENCODING:gzip, deflate, br
HTTP_ACCEPT_LANGUAGE:en-US,en;q=0.9
HTTP_COOKIE:        _ga=; __utmz=71864394.1516061264.15.2.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); __utma=71864394.571984562.1515382139.1517611392.1519680375.20; _gid=; SSESSa4a60562654789a08301f7471b7d6ab6=fTLfI44E3JnUsnft0ToYJPWDY_T5xDHOB-145oGkfAo; has_js=1
HTTP_X_HTTPS:       1
PATH:               /sbin:/usr/sbin:/bin:/usr/bin
SERVER_SIGNATURE:
SERVER_SOFTWARE:    Apache
SERVER_NAME:        crm.domain.org
SERVER_ADDR:        0.0.0.0
SERVER_PORT:        443
REMOTE_ADDR:        0.0.0.0
DOCUMENT_ROOT:      /home/domain/public_html
REQUEST_SCHEME:     https
CONTEXT_PREFIX:     /cgi-sys
CONTEXT_DOCUMENT_ROOT:/usr/local/cpanel/cgi-sys/
SERVER_ADMIN:       webmaster@crm.domain.org
SCRIPT_FILENAME:    /home/domain/public_html/index.php
REMOTE_PORT:        38246
REDIRECT_URL:       /index.php
GATEWAY_INTERFACE:  CGI/1.1
SERVER_PROTOCOL:    HTTP/1.1
REQUEST_METHOD:     POST
QUERY_STRING:
REQUEST_URI:        /civicrm/event/register
SCRIPT_NAME:        /index.php
ORIG_SCRIPT_FILENAME:/usr/local/cpanel/cgi-sys/ea-php70
ORIG_PATH_INFO:     /index.php
ORIG_PATH_TRANSLATED:/home/domain/public_html/index.php
ORIG_SCRIPT_NAME:   /cgi-sys/ea-php70
PHP_SELF:           /index.php
REQUEST_TIME_FLOAT: 1519744725.1223
REQUEST_TIME:       1519744725



***BACKTRACE***
#0 /home/domain/public_html/sites/default/files/civicrm/ext/ca.bidon.reporterror/reporterror.php(266): reporterror_civicrm_generatereport("Orgnaization", (Array:2), NULL, (Array:0))
#1 /home/domain/public_html/sites/all/modules/civicrm/CRM/Core/Error.php(365): reporterror_civicrm_handler((Array:2))
#2 /home/domain/public_html/sites/all/modules/civicrm/CRM/Utils/Request.php(120): CRM_Core_Error::fatal("Could not find valid value for id")
#3 /home/domain/public_html/sites/all/modules/civicrm/CRM/Event/StateMachine/Registration.php(52): CRM_Utils_Request::retrieve("id", "Positive", Object(CRM_Event_Controller_Registration), TRUE)
#4 /home/domain/public_html/sites/all/modules/civicrm/CRM/Event/Controller/Registration.php(47): CRM_Event_StateMachine_Registration->__construct(Object(CRM_Event_Controller_Registration), TRUE)
#5 /home/domain/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(304): CRM_Event_Controller_Registration->__construct("Event Registration", TRUE, "null", NULL, "false")
#6 /home/domain/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:15))
#7 /home/domain/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#8 /home/domain/public_html/sites/all/modules/civicrm/drupal/civicrm.module(448): CRM_Core_Invoke::invoke((Array:3))
#9 /home/domain/public_html/includes/menu.inc(527): civicrm_invoke("event", "register")
#10 /home/domain/public_html/index.php(21): menu_execute_active_handler()
#11 {main}


***POST***
qfKey:              63ab4dbb89206e52bf2de9d34e150756_2611
entryURL:           https://crm.domain.org/civicrm/event/register?reset=1&amp;id=112
hidden_processor:   1
scriptFee:
scriptArray:
priceSetId:         164
payment_processor_id:1
bypass_payment:
_qf_default:        Register:upload
MAX_FILE_SIZE:      2097152
additional_participants:1
first_name:         FirstName
last_name:         LastName 
email-Primary:      email@email.com
phone-1-2:          7201234567
custom_134:         Array
(
    [Board Member] =>
    [Board President] =>
    [Project Captain] =>
    [Recipient] =>
    [Sponsor] =>
    [Volunteer] =>
    [Proud Supporter] => 1
    [Other] => 1
)
custom_135:         Proud collaborator!
custom_139:
custom_136:         Continued independence, enrichment and happiness for ---- recipients.
custom_138:
price_294:          2
price_289:
price_290:
price_291:
price_292:
price_293:
credit_card_type:   Amex
credit_card_number: 300000000000000
cvv2:               4000
credit_card_exp_date:Array
(
    [M] => 3
    [Y] => 2020
)

billing_first_name: FirstName
billing_middle_name:
billing_last_name:  LastName
billing_street_address-5:134 123 Street
billing_city-5:     Denver
billing_country_id-5:1228
billing_state_province_id-5:1005
billing_postal_code-5:80223
_qf_Register_upload:Continue



***FULL BACKTRACE***
**next call**
file:               /home/domain/public_html/sites/default/files/civicrm/ext/ca.bidon.reporterror/reporterror.php
line:               266
function:           reporterror_civicrm_generatereport
args:               Array
(
    [0] => Organization
    [1] => Array
        (
            [message] => Could not find valid value for id
            [code] =>
        )

    [2] =>
    [3] => Array
        (
        )

)


**next call**
file:               /home/domain/public_html/sites/all/modules/civicrm/CRM/Core/Error.php
line:               365
function:           reporterror_civicrm_handler
args:               Array
(
    [0] => Array
        (
            [message] => Could not find valid value for id
            [code] =>
        )

)


**next call**
file:               /home/domain/public_html/sites/all/modules/civicrm/CRM/Utils/Request.php
line:               120
function:           fatal
class:              CRM_Core_Error
type:               ::
args:               Array
(
    [0] => Could not find valid value for id
)


**next call**
file:               /home/domain/public_html/sites/all/modules/civicrm/CRM/Event/StateMachine/Registration.php
line:               52
function:           retrieve
class:              CRM_Utils_Request
type:               ::
args:               Array
(
    [0] => id
    [1] => Positive
    [2] => CRM_Event_Controller_Registration Object
        (
            [_title:protected] => Event Registration
            [_key] => 63ab4dbb89206e52bf2de9d34e150756_2611
            [_scope:protected] => CRM_Event_Controller_Registration_63ab4dbb89206e52bf2de9d34e150756_2611
            [_stateMachine:protected] =>
            [_embedded:protected] =>
            [_skipRedirection:protected] =>
            [_print] => 0
            [_generateQFKey] => 1
            [_QFResponseType] => html
            [_parent:protected] =>
            [_destination] =>
            [_entryURL] => https://crm.domain.org/civicrm/event/register?reset=1&amp;id=112
            [_pages] => Array
                (
                )

            [_actions] => Array
                (
                )

            [_name] => CRM_Event_Controller_Registration_63ab4dbb89206e52bf2de9d34e150756_2611
            [_modal] => null
            [_actionName] =>
        )

    [3] => 1
)


**next call**
file:               /home/domain/public_html/sites/all/modules/civicrm/CRM/Event/Controller/Registration.php
line:               47
function:           __construct
class:              CRM_Event_StateMachine_Registration
object:             CRM_Event_StateMachine_Registration Object
(
    [_controller:protected] => CRM_Event_Controller_Registration Object
        (
            [_title:protected] => Event Registration
            [_key] => 63ab4dbb89206e52bf2de9d34e150756_2611
            [_scope:protected] => CRM_Event_Controller_Registration_63ab4dbb89206e52bf2de9d34e150756_2611
            [_stateMachine:protected] =>
            [_embedded:protected] =>
            [_skipRedirection:protected] =>
            [_print] => 0
            [_generateQFKey] => 1
            [_QFResponseType] => html
            [_parent:protected] =>
            [_destination] =>
            [_entryURL] => https://crm.domain.org/civicrm/event/register?reset=1&amp;id=112
            [_pages] => Array
                (
                )

            [_actions] => Array
                (
                )

            [_name] => CRM_Event_Controller_Registration_63ab4dbb89206e52bf2de9d34e150756_2611
            [_modal] => null
            [_actionName] =>
        )

    [_states:protected] => Array
        (
        )

    [_pages:protected] =>
    [_pageNames:protected] =>
    [_action:protected] => 1
    [_name:protected] =>
)

type:               ->
args:               Array
(
    [0] => CRM_Event_Controller_Registration Object
        (
            [_title:protected] => Event Registration
            [_key] => 63ab4dbb89206e52bf2de9d34e150756_2611
            [_scope:protected] => CRM_Event_Controller_Registration_63ab4dbb89206e52bf2de9d34e150756_2611
            [_stateMachine:protected] =>
            [_embedded:protected] =>
            [_skipRedirection:protected] =>
            [_print] => 0
            [_generateQFKey] => 1
            [_QFResponseType] => html
            [_parent:protected] =>
            [_destination] =>
            [_entryURL] => https://crm.domain.org/civicrm/event/register?reset=1&amp;id=112
            [_pages] => Array
                (
                )

            [_actions] => Array
                (
                )

            [_name] => CRM_Event_Controller_Registration_63ab4dbb89206e52bf2de9d34e150756_2611
            [_modal] => null
            [_actionName] =>
        )

    [1] => 1
)


**next call**
file:               /home/domain/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php
line:               304
function:           __construct
class:              CRM_Event_Controller_Registration
object:             CRM_Event_Controller_Registration Object
(
    [_title:protected] => Event Registration
    [_key] => 63ab4dbb89206e52bf2de9d34e150756_2611
    [_scope:protected] => CRM_Event_Controller_Registration_63ab4dbb89206e52bf2de9d34e150756_2611
    [_stateMachine:protected] =>
    [_embedded:protected] =>
    [_skipRedirection:protected] =>
    [_print] => 0
    [_generateQFKey] => 1
    [_QFResponseType] => html
    [_parent:protected] =>
    [_destination] =>
    [_entryURL] => https://crm.domain.org/civicrm/event/register?reset=1&amp;id=112
    [_pages] => Array
        (
        )

    [_actions] => Array
        (
        )

    [_name] => CRM_Event_Controller_Registration_63ab4dbb89206e52bf2de9d34e150756_2611
    [_modal] => null
    [_actionName] =>
)

type:               ->
args:               Array
(
    [0] => Event Registration
    [1] => 1
    [2] => null
    [3] =>
    [4] => false
)


**next call**
file:               /home/domain/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php
line:               84
function:           runItem
class:              CRM_Core_Invoke
type:               ::
args:               Array
(
    [0] => Array
        (
            [id] => 254
            [domain_id] => 1
            [path] => civicrm/event/register
            [title] => Event Registration
            [access_callback] => 1
            [access_arguments] => Array
                (
                    [0] => Array
                        (
                            [0] => access CiviCRM
                            [1] => access CiviEvent
                        )

                    [1] => and
                )

            [page_callback] => CRM_Event_Controller_Registration
            [breadcrumb] => Array
                (
                    [0] => Array
                        (
                            [title] => CiviCRM
                            [url] => /civicrm?reset=1
                        )

                    [1] => Array
                        (
                            [title] => CiviEvent Dashboard
                            [url] => /civicrm/event?reset=1
                        )

                )

            [component_id] => 1
            [is_public] => 1
            [is_ssl] => 1
            [weight] => 1
            [type] => 1
            [page_type] => 0
            [page_arguments] =>
        )

)


**next call**
file:               /home/domain/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php
line:               52
function:           _invoke
class:              CRM_Core_Invoke
type:               ::
args:               Array
(
    [0] => Array
        (
            [0] => civicrm
            [1] => event
            [2] => register
        )

)


**next call**
file:               /home/domain/public_html/sites/all/modules/civicrm/drupal/civicrm.module
line:               448
function:           invoke
class:              CRM_Core_Invoke
type:               ::
args:               Array
(
    [0] => Array
        (
            [0] => civicrm
            [1] => event
            [2] => register
        )

)


**next call**
file:               /home/domain/public_html/includes/menu.inc
line:               527
function:           civicrm_invoke
args:               Array
(
    [0] => event
    [1] => register
)


**next call**
file:               /home/domain/public_html/index.php
line:               21
function:           menu_execute_active_handler
args:               Array
(
)

**Comment by stevekessler** [comment]
We have figured out that these emails are sent when someone exits without confirming their registration.  Hope this helps with a solution.  

Thanks,
Steve

**Comment by mlutfy** [comment]
Hi Steve,

The issue should now be fixed (in the latest `master` branch of this extension).

Testing with the dummy processor, when I enable "Display POST data in e-mails?", I get:

```
credit_card_type:   Visa
credit_card_number: 4111[removed]
cvv2: [removed]
```

Can you test & confirm? If it works, I will release a new version of the extension.

**Comment by mlutfy** [comment]
(closed by mistake)

PS: in the new `master`, you will have to run `composer install`, because reporterror now supports monolog/gelf. c.f. #29

**Comment by mlutfy** [comment]
Hi Steve,

Any luck testing the new version?

Mathieu

**Comment by stevekessler** [comment]
I will try and test this today.

Thanks,
Steve

**Comment by stevekessler** [comment]
@mlutfy I have not been able to recreate the issue in dev.  I am still not entirely sure what someone does to produce the error.  

I will get this on our production site probably tonight and can open a ticket if the problem comes back.  

Thanks,
Steve

**Comment by stevekessler** [comment]
I had an example of this in production and it worked as expected.  Thanks again!
